 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();
var url = require('url');

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    });

app.get('/*', function(req, res) {
  let urlRequest = url.parse(req.url, true);
  let newDate;
  let pathName;
  let jsonTime;
  let months = ["Jan", "Feb", "March", "April", "May", "June", "July", "August", "Sep", "Oct", "Nov", "Dec"];
  let month;
  let year;
  pathName = urlRequest.pathname;
  pathName = urlRequest.pathname.slice(1, pathName.length);
  if (!(isNaN(pathName))) {
    newDate = new Date(pathName * 1000);
  } else {
    newDate = new Date(decodeURI(pathName));
  }
  month = months[newDate.getMonth()];
  year = newDate.getFullYear();
  if (!(isNaN(newDate.getTime()))) {
    let jsonTime = {
      "unix": newDate.getTime() / 1000,
      "natural": `${month} ${newDate.getDay()}, ${year}`
    };
    res.writeHead(200, {'Content-Type': 'application/json' });
    res.write(JSON.stringify(jsonTime));
    res.end();
  } else {
    res.end();
  }
});

// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

